name: ci

on:
  push:
    branches:
      - main
    paths:
      - postgres-s3-backup/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [12, 13, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push versions
        uses: docker/build-push-action@v2
        with:
          context: postgres-s3-backup
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/postgres-s3-backup:${{ matrix.postgres }}
  tag:
    needs: build
    runs-on: ubuntu-latest
    env:
      POSTGRES_LATEST: 14
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Tag Latest
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/postgres-s3-backup:${{ env.POSTGRES_LATEST }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/postgres-s3-backup:${{ env.POSTGRES_LATEST }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/postgres-s3-backup:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/postgres-s3-backup:latest